// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumTrack: typeof import('./src/components/Track/AlbumTrack.vue')['default']
    CorusalSection: typeof import('./src/components/CorusalSection.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    MvCover: typeof import('./src/components/MvCover.vue')['default']
    MyTrackItem: typeof import('./src/components/Track/MyTrackItem.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    Section: typeof import('./src/components/Section.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    SwitchTheme: typeof import('./src/components/SwitchTheme.vue')['default']
    Track: typeof import('./src/components/Track/Track.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
