// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumItem: typeof import('./src/components/AlbumItem/AlbumItem.vue')['default']
    Cover: typeof import('./src/components/Cover/Cover.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    Explore: typeof import('./src/views/Explore/Explore.vue')['default']
    ExploreTag: typeof import('./src/views/Explore/ExploreTag/ExploreTag.vue')['default']
    Home: typeof import('./src/views/Home/Home.vue')['default']
    HomeAlbumNewest: typeof import('./src/views/Home/HomeAlbumNewest.vue')['default']
    HomeRankList: typeof import('./src/views/Home/HomeRankList.vue')['default']
    HomeRecomAlbum: typeof import('./src/views/Home/HomeRecomAlbum.vue')['default']
    HomeRecomArtist: typeof import('./src/views/Home/HomeRecomArtist.vue')['default']
    ListItem: typeof import('./src/components/PlayListItem/ListItem.vue')['default']
    Login: typeof import('./src/views/Login/Login.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    My: typeof import('./src/views/My/My.vue')['default']
    NavBar: typeof import('./src/layout/NavBar.vue')['default']
    NavBarCenter: typeof import('./src/components/NavBar/NavBarCenter.vue')['default']
    NavBarLeft: typeof import('./src/components/NavBar/NavBarLeft.vue')['default']
    NavBarRight: typeof import('./src/components/NavBar/NavBarRight.vue')['default']
    NewAlbum: typeof import('./src/views/NewAlbum/NewAlbum.vue')['default']
    Personalized: typeof import('./src/views/Home/Personalized/Personalized.vue')['default']
    PersonalizedDaily: typeof import('./src/views/Home/Personalized/PersonalizedDaily.vue')['default']
    PersonalizeNewSong: typeof import('./src/views/Home/Personalized/PersonalizeNewSong.vue')['default']
    PlayList: typeof import('./src/views/PlayList/PlayList.vue')['default']
    PlayListItem: typeof import('./src/components/PlayListItem/PlayListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    Swiper: typeof import('./src/views/Home/Swiper/Swiper.vue')['default']
    SwitchTheme: typeof import('./src/components/NavBar/NavBarRightComp/SwitchTheme.vue')['default']
    TagSelector: typeof import('./src/views/Explore/TagSelector/TagSelector.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
